services:
  - type: web
    name: youtube-downloader-backend
    env: node
    buildCommand: npm install && chmod +x install-yt-dlp.sh && ./install-yt-dlp.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 